# Generated by Django 3.0.5 on 2020-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donatethe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdname', models.CharField(max_length=100)),
                ('tdaddress', models.CharField(max_length=1000)),
                ('tdorphanage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='youdonate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ydname', models.CharField(max_length=100)),
                ('ydaddress', models.CharField(max_length=1000)),
                ('yddaddress', models.CharField(max_length=1000)),
                ('ydfood', models.CharField(max_length=1000)),
            ],
        ),
    ]
