# Generated by Django 3.0.5 on 2020-08-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatethe',
            name='tdcontact',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donatethe',
            name='tdpeople',
            field=models.IntegerField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youdonate',
            name='ydcontact',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youdonate',
            name='ydpeople',
            field=models.IntegerField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
