# Generated by Django 3.0.5 on 2020-07-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_breakfast_dinner_lunch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='breakfast',
        ),
        migrations.DeleteModel(
            name='dinner',
        ),
        migrations.DeleteModel(
            name='lunch',
        ),
    ]
