# Generated by Django 3.0.5 on 2020-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200715_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastt',
            name='qtyd',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='breakfastt',
            name='qtyi',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='breakfastt',
            name='qtypon',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='breakfastt',
            name='qtypoo',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='breakfastt',
            name='qtyth',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='breakfastt',
            name='qtyup',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dinnerr',
            name='qtyd',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dinnerr',
            name='qtyi',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dinnerr',
            name='qtypon',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dinnerr',
            name='qtypoo',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dinnerr',
            name='qtyth',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dinnerr',
            name='qtyup',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lunchh',
            name='qtycurd',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lunchh',
            name='qtydal',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lunchh',
            name='qtylem',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lunchh',
            name='qtytam',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lunchh',
            name='qtyvr',
            field=models.IntegerField(max_length=100),
        ),
    ]
