# Generated by Django 3.0.5 on 2020-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200717_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='img1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idliimg', models.ImageField(upload_to='pics')),
                ('dosaimg', models.ImageField(upload_to='pics')),
                ('pongimg', models.ImageField(upload_to='pics')),
                ('uthimg', models.ImageField(upload_to='pics')),
                ('upmaimg', models.ImageField(upload_to='pics')),
                ('pooriimg', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='img2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curdimg', models.ImageField(upload_to='pics')),
                ('dalimg', models.ImageField(upload_to='pics')),
                ('lemimg', models.ImageField(upload_to='pics')),
                ('tamimg', models.ImageField(upload_to='pics')),
                ('vrimg', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='img3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idliimg', models.ImageField(upload_to='pics')),
                ('dosaimg', models.ImageField(upload_to='pics')),
                ('pongimg', models.ImageField(upload_to='pics')),
                ('uthimg', models.ImageField(upload_to='pics')),
                ('upmaimg', models.ImageField(upload_to='pics')),
                ('pooriimg', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='dosaimg',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='idliimg',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='pongimg',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='pooriimg',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='upmaimg',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='uthimg',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='dosaimg',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='idliimg',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='pongimg',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='pooriimg',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='upmaimg',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='uthimg',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='curdimg',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='dalimg',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='lemimg',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='tamimg',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='vrimg',
        ),
    ]
