# Generated by Django 3.0.5 on 2020-07-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200717_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfastt',
            name='Dosa',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='Idli',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='Pongal',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='Poori',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='Upma',
        ),
        migrations.RemoveField(
            model_name='breakfastt',
            name='Uthapam',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='Dosa',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='Idli',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='Pongal',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='Poori',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='Upma',
        ),
        migrations.RemoveField(
            model_name='dinnerr',
            name='Uthapam',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='Curd',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='Dal',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='Lemon',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='Tamarind',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='Vegrice',
        ),
        migrations.RemoveField(
            model_name='lunchh',
            name='qtyvr',
        ),
    ]
