# Generated by Django 3.0.5 on 2020-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_lunchh_qtyvr'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofc', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
